# Generated by Django 5.1.7 on 2025-07-27 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_dependent_guardian'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_types', to='core.guardian')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('dependent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='core.dependent')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='core.guardian')),
                ('message_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.messagetype')),
            ],
        ),
    ]
