# Generated by Django 5.1.7 on 2025-08-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_messagetype_guardian_messagetype_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetype',
            old_name='label',
            new_name='label_ar',
        ),
        migrations.AddField(
            model_name='messagetype',
            name='audio_file_ar',
            field=models.FileField(blank=True, null=True, upload_to='audio_messages/ar/'),
        ),
        migrations.AddField(
            model_name='messagetype',
            name='audio_file_en',
            field=models.FileField(blank=True, null=True, upload_to='audio_messages/en/'),
        ),
        migrations.AddField(
            model_name='messagetype',
            name='label_en',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
