# Generated by Django 5.1.7 on 2025-08-16 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_dependent_interest_field'),
        ('message', '0003_rename_label_messagetype_label_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianMessageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_messages', to='core.guardian')),
                ('message_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_messages', to='message.messagetype')),
            ],
            options={
                'unique_together': {('guardian', 'message_type')},
            },
        ),
    ]
