# Generated by Django 5.1.7 on 2025-08-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_alter_message_message_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_sms',
            field=models.BooleanField(default=False),
        ),
    ]
