# Generated by Django 5.1.7 on 2025-08-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_message_is_sms'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
    ]
