# Generated by Django 5.1.7 on 2025-08-17 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_message_is_emergency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_emergency',
            new_name='is_voice',
        ),
    ]
