# Generated by Django 5.1.7 on 2025-08-17 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0008_rename_is_emergency_message_is_voice'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='message.guardianmessagetype'),
        ),
    ]
