# Generated by Django 5.1.7 on 2025-08-23 23:38

import message.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0009_message_is_emergency_alter_message_message_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagetype',
            name='audio_file_ar',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=message.models.MessageType.rename_audio_file_ar),
        ),
        migrations.AlterField(
            model_name='messagetype',
            name='audio_file_en',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=message.models.MessageType.rename_audio_file_en),
        ),
    ]
