# Generated by Django 5.1.7 on 2025-07-27 02:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependent',
            name='user',
        ),
        migrations.AddField(
            model_name='dependent',
            name='disability_type',
            field=models.CharField(choices=[('motor', 'Motor'), ('verbal', 'Verbal'), ('cognitive', 'Cognitive'), ('visual', 'Visual'), ('hearing', 'Hearing'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='dependent',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dependent',
            name='control_method',
            field=models.CharField(choices=[('eye', 'Eye Only'), ('eye_lip', 'Eye and Lips')], max_length=20),
        ),
    ]
