# Generated by Django 5.1.7 on 2025-07-27 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_dependent_user_dependent_disability_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='guardian',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='core.guardian'),
        ),
    ]
