# Generated by Django 5.1.7 on 2025-07-30 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_dependent_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependent',
            name='degree_type',
            field=models.CharField(blank=True, choices=[('bachelor', 'Bachelor'), ('master', 'Master'), ('phd', 'PhD'), ('diploma', 'Diploma'), ('other', 'Other')], max_length=100, null=True, verbose_name='Degree Type'),
        ),
        migrations.AddField(
            model_name='dependent',
            name='interest_field',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Field of Interest'),
        ),
        migrations.AddField(
            model_name='dependent',
            name='marital_status',
            field=models.CharField(choices=[('single', 'Single'), ('married', 'Married')], default='single', max_length=20),
        ),
    ]
