# Generated by Django 5.1.7 on 2025-07-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_dependent_degree_type_dependent_interest_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='guardian_code_hashed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
