# Generated by Django 5.1.7 on 2025-07-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependent',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
            preserve_default=False,
        ),
    ]
