# Generated by Django 5.1.7 on 2025-07-30 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_disabilitytype_alter_dependent_disability_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='disabilitytype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
