# Generated by Django 5.1.7 on 2025-08-04 22:31

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_disabilitytype_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='interest_field',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('tech', 'Tech, Cybersecurity, and AI'), ('design', 'Design, Graphics, and UX'), ('business', 'Business, Entrepreneurship, and Marketing'), ('medical', 'Medicine and Health'), ('law', 'Law and Regulations'), ('education', 'Education, Training, and Mentoring'), ('engineering', 'Engineering (All Types)'), ('science', 'Natural Sciences (Physics, Chemistry, Biology)'), ('earth', 'Earth and Environmental Sciences'), ('languages', 'Languages and Literature')], max_length=78, null=True, verbose_name='Field of Interest'),
        ),
    ]
