# Generated by Django 5.1.7 on 2025-08-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_dependent_interest_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependent',
            name='registration_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Device Registration ID'),
        ),
    ]
