# Generated by Django 5.1.7 on 2025-08-24 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_guardian_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='registration_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Device Registration ID'),
        ),
    ]
