# Generated by Django 5.1.7 on 2025-09-09 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notification_dependent_msg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GuardianMessageDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_count', models.PositiveIntegerField(default=10)),
                ('guardian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_defaults', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
