# Generated by Django 5.1.7 on 2025-09-09 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_appsetting_guardianmessagedefault'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardianmessagedefault',
            name='guardian',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_defaults', to='core.guardian'),
        ),
    ]
