# Generated by Django 5.1.7 on 2025-09-09 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_guardianmessagedefault_guardian'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppSetting',
        ),
        migrations.DeleteModel(
            name='GuardianMessageDefault',
        ),
    ]
