# Generated by Django 5.1.7 on 2025-09-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_delete_appsetting_delete_guardianmessagedefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='version',
            field=models.CharField(default='v1', max_length=10, verbose_name='App Version'),
            preserve_default=False,
        ),
    ]
