# Generated by Django 5.1.7 on 2025-09-09 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_appsettings_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianMessageDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_per_month', models.PositiveIntegerField(default=0)),
                ('app_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_defaults', to='core.appsettings')),
                ('guardian', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message_defaults', to='core.guardian')),
            ],
        ),
    ]
