# Generated by Django 5.1.7 on 2025-09-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_guardianmessagedefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianmessagedefault',
            name='notified_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('general', 'General'), ('new_message', 'New Message'), ('package_expired', 'Package Expired'), ('package_renewed', 'Package Renewed')], max_length=100, null=True, verbose_name='type'),
        ),
    ]
