# Generated by Django 5.1.7 on 2025-09-27 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_guardianmessagedefault_notified_expired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsettings',
            name='pending_guardian_increment',
            field=models.IntegerField(default=0, help_text='Number of additional messages to add to guardians with expired packages when they renew.', verbose_name='Pending Guardian Increment'),
        ),
    ]
