# Generated by Django 5.1.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependent',
            name='degree_type_other',
            field=models.CharField(blank=True, help_text='Custom degree type when "other" is selected', max_length=255, null=True, verbose_name='Custom Degree Type'),
        ),
    ]

